version: '3.8'  # 使用版本3.8，但你可以根据需要选择适合你Docker环境的版本

services:
  ubuntu-desktop:
    image: public.ecr.aws/lensfa/workos-kasm:ub22
    container_name: work-container  # 可以指定一个容器名称
    volumes:
      - /dev/shm:/dev/shm  # 映射共享内存
      - /home/ec2-user/work:/home/kasm-user/work  # 映射数据卷
    # network_mode: host  # 设置网络模式为 host
    # 指定端口，让容器只使用ipv4网络
    ports:
      - "3389:3389"

    # 只启动图型界面 不启动ssh
    entrypoint: /gui.sh
    restart: unless-stopped  # 设置重启策略